### ISSUE TITLE
About page design

### ISSUE THREAD

**Issue by Brochua** [Porogoramer/porogoramer.com#37]
## Description

Design about us page on figma.

## Requirements

- List of team members (Should be made of some card or list item that could be made into a component)
- Highlight project?

**Comment by Yan2arb4** [comment]
Finished design of about us page. All pictures are placeholders don't worry about that. 
Link to design : https://www.figma.com/proto/mdPZnwNCEw8EnEj8L0Riq5/Porogo-website?node-id=1038-1332&t=QI5CeMhF3s9pBm8e-0&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=522%3A217

Reviews/questions would be appreciated.

**Comment by Brochua** [comment]
I really like the design, but would you reuse the project card that rida created? 
![image](https://github.com/user-attachments/assets/3d8a0326-607e-40ec-ba30-e58051f41461)

**Comment by Yan2arb4** [comment]
Yes we would, I like its design but Id make the picture a rectangle instead of a circle.
