### ISSUE TITLE
Header layout

### ISSUE THREAD

**Issue by Sprytte** [Porogoramer/porogoramer.com#9]
**Description**
Create the header and give it the basic layout while following design.

**Requirements**

1. Create header component/class
2. Add logo
3. Add nav links
4. Add icon for dark/light mode
5. Add eng/fr option

**Comment by Yan2arb4** [comment]
Header layout implemented.
Includes :
-Redirection with links
-Fire SCSS
-Tests
Excludes :
-Functioning LightMode/Darkmode
-Functioning Translation button
